# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170730_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(null=True, upload_to='media/blog/cover'),
        ),
    ]
