# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField(max_length=10)),
                ('linkdin', models.CharField(max_length=50)),
                ('github', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=40)),
                ('clas', models.CharField(max_length=20)),
                ('year', models.IntegerField(max_length=4)),
            ],
        ),
    ]
