# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='college',
            field=models.CharField(default='College of Engineering Chengannur', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='github',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='linkdin',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.IntegerField(),
        ),
    ]
