# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_dp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dp',
            name='id',
        ),
        migrations.AddField(
            model_name='dp',
            name='dpid',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
