# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_user_dp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.CharField(default='passionate developer. Skilled programmer . Devcom member', max_length=140),
        ),
    ]
