# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_user_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover',
            field=models.ImageField(null=True, upload_to='media/cover'),
        ),
    ]
