# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='desc',
            field=models.CharField(default='devcom is a really innovative idea to nurture future developers', max_length=1000),
            preserve_default=False,
        ),
    ]
