# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
