# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_stage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover',
            field=models.ImageField(null=True, upload_to='media/blog/cover'),
        ),
    ]
